package com.celecavac.advent2;

public class Inputs {
    public static String input1 = "oeambtcgjqnzhgkdylfapoiusr\n" +
            "oewmbtcxjqnzhgvdyltapvqusr\n" +
            "oewmbtchjqnzigkdylfapviuse\n" +
            "oeimbucxjqnzhgkdyyfapviusr\n" +
            "fewmbtcxjqndhgcdylfapviusr\n" +
            "oevgbtccjqnzhgkdylfapviusr\n" +
            "oewmbtcxjqnzhnkdylmapvpusr\n" +
            "oewmbtcxjqnzhxkdyldapvirsr\n" +
            "oewmutccjqnzngkdylfapviusr\n" +
            "oewmbtcxbqnzhgkdsliapviusr\n" +
            "ozwmbtfxjqnzcgkdylfapviusr\n" +
            "oewmbtdxjqnzhgkdypfapsiusr\n" +
            "oeylbtcxjqnzhgyyylfapviusr\n" +
            "oewmbtcxjqnzhgkdrlfakuiusr\n" +
            "oewmbtcujqnxhgkdylfadviusr\n" +
            "oewmbtcxlqpzhgkdylfaaviusr\n" +
            "oewmztcxjqnzhgkdylfqpliusr\n" +
            "oeembtcxjqnzhgkdtlmapviusr\n" +
            "onwmbtcxjqnqhgkdylfapdiusr\n" +
            "oewmbtcxnqnzhgkdylfapsbusr\n" +
            "oeoibtjxjqnzhgkdylfapviusr\n" +
            "oxwmbtcxjqnzhgkdylfapcipsr\n" +
            "oewmbtoxbqnzhgzdylfapviusr\n" +
            "okwubtcxjqnzhgkdylfapiiusr\n" +
            "oewmbtcxjqnzhgodylfapnicsr\n" +
            "oewmitcxjqnzhgkdylfaphlusr\n" +
            "oewmbtaxjqnzhgkhylfapveusr\n" +
            "oewmftcbjqnzhgkdylfapviurr\n" +
            "oewmbtcujqnzbgkdylfapliusr\n" +
            "oeevbtcxjqnzhgkdylfapniusr\n" +
            "oewmbtcxjqnvhgkdylfapnpusr\n" +
            "oewabtcxjqnzhgddylfapviust\n" +
            "oewmbtyxjqnzhgkdvlfapvinsr\n" +
            "jewmbtcxjonzhzkdylfapviusr\n" +
            "oewmbrcxjqnzxgkdylfapoiusr\n" +
            "dewmbtmxjqnzhgkdyvfapviusr\n" +
            "oewmbtctjqnzhgkdmlfapvihsr\n" +
            "oewmbjcxjqnzhgvdylfapviurr\n" +
            "oewmbtcxjqnzhgcdxlfapvfusr\n" +
            "oewmbucxjqnzhgkdyltapvifsr\n" +
            "gewmbtcejqezhgkdylfapviusr\n" +
            "oewebtcxjznzhgkdylfapvhusr\n" +
            "oewmjtcxjqnzhgkdycfakviusr\n" +
            "oewmbtcxjtnvhgkdylfabviusr\n" +
            "oewmbtcxjqnthgkgclfapviusr\n" +
            "hewmbtcxjqnzhgkdwlfapziusr\n" +
            "oewmbtcxjqnzhgkdylfqpviysf\n" +
            "oewmbtcxjvnzhgmdylfapviuse\n" +
            "oewmbtcxjqnphgkdymzapviusr\n" +
            "oewmbtcxjqnzwmkdylfapvbusr\n" +
            "oewmbthxjqnzhgkdylfatvilsr\n" +
            "oewmbtcxaznzhgkhylfapviusr\n" +
            "zewmbscxjqnzhgkdylfatviusr\n" +
            "oewmbecyaqnzhgkdylfapviusr\n" +
            "oewmbtnxjqnzhekxylfapviusr\n" +
            "oewmbtcxjqczhgkdyltnpviusr\n" +
            "yewmbecxjnnzhgkdylfapviusr\n" +
            "oewmbocxjqnzhgkyylfapviusv\n" +
            "oewmxtcxjqnzhgkkylfspviusr\n" +
            "oiwmbtcxjqnzhgkdydfapvgusr\n" +
            "oewmbtcxjqnzngydylfwpviusr\n" +
            "oewmctcxjqnzhgkdelfapviasr\n" +
            "oewmbtcxjqnzhgxdwmfapviusr\n" +
            "oewmntcxjqnzhgkdylfamviusw\n" +
            "oewmatcxjqbzhgkdylfapvhusr\n" +
            "oewmbtcxjqnqhmkdyluapviusr\n" +
            "opwmbtcxjqnzhgkdywfapvilsr\n" +
            "omwmbtcxjqnlhgkdylyapviusr\n" +
            "oewmltcxoqnzhgkdylfapvfusr\n" +
            "oewmbtcxjqtzhgkdyyoapviusr\n" +
            "oewmbtcxjqnzhrkdzlffpviusr\n" +
            "oewmbtqxyqnzhgkdylfalviusr\n" +
            "oeuzbtcxlqnzhgkdylfapviusr\n" +
            "oewmbtcxjqnzhtxdylflpviusr\n" +
            "oewmdtfxjqnzhgkdylfapviufr\n" +
            "ojwmbtcxjqnzhgkdylfypviqsr\n" +
            "oewmbtcxjqnzhgkdylfapvivuf\n" +
            "oewmjtcsjqnzxgkdylfapviusr\n" +
            "ohembtcxjqnzhnkdylfapviusr\n" +
            "oewmptcajqnzhgkdylfapviusd\n" +
            "oewmbtcxjcnwhgkbylfapviusr\n" +
            "oewmbtcxjqnzhgddnlfapvqusr\n" +
            "oewmbtcfjqnzhgkdypfapvzusr\n" +
            "oewdbtccjqnzhgfdylfapviusr\n" +
            "oewmbtcxjpnzhgkdplfaqviusr\n" +
            "oepmbhcxjqnzhgkdylfaaviusr\n" +
            "oewmbtcwjqxzhgkwylfapviusr\n" +
            "oewmatcxjqnchgkdylfapvifsr\n" +
            "omwmbncxjqnzhgkdylfapviuyr\n" +
            "sewmbsckjqnzhgkdylfapviusr\n" +
            "oewubtcxjqnzhgkdyluapvausr\n" +
            "ohwmbtcxqqhzhgkdylfapviusr\n" +
            "oewmbtcxjqnzhgkpylfapnissr\n" +
            "eewmbccxjqnzhgkdylbapviusr\n" +
            "oewmitcyjqnzhgkdylkapviusr\n" +
            "oewmbtcxjvnzhgkdyjfvpviusr\n" +
            "oewmbtcxjqmzhgkdyefagviusr\n" +
            "oewmbtcvjqnzhgkdylpapviufr\n" +
            "oewmbtcxjrnkhgkdylfapsiusr\n" +
            "oewmbtcxjqnzygkdylfaxvipsr\n" +
            "oexmbtcxjqczhgkdyloapviusr\n" +
            "oewmbtcxjqnlhtkdylfapvmusr\n" +
            "oewmbtcxdqjzdgkdylfapviusr\n" +
            "oewmbtclgqnzhgkdylfabviusr\n" +
            "oewmbtvfjqnzhgkdylfapviulr\n" +
            "oewmbtcxjqnzhgkdyllarvijsr\n" +
            "oewmbtyxjqnzhgpdylxapviusr\n" +
            "oeylbtcxjqnzhgkyylfapviusr\n" +
            "oewmbtctjqnzhjkdylfapviulr\n" +
            "oermatcxjqnzhgkdylzapviusr\n" +
            "oewmbtcxjqnztgkdzlfapviutr\n" +
            "oewlbtcxjqnztgkvylfapviusr\n" +
            "oewmbtcxjqzvhgkdylfapviusk\n" +
            "oewmbtcxjqnzmgkdyldapvilsr\n" +
            "felmbtcxjqnzhgkdylfapviusl\n" +
            "oewmbtcxjgnzhgkjylfaeviusr\n" +
            "ovwmbtcxjqpzhgkdylfapvizsr\n" +
            "eewmbtcpjqnzhgkdylfapvijsr\n" +
            "oewmbzcxjqnzhgkdylfaeviutr\n" +
            "tewmbtcljqhzhgkdylfapviusr\n" +
            "oewmbtcujqnzhgkdnliapviusr\n" +
            "oewmbtcljqnzhskdylfapvgusr\n" +
            "oewmbtchjqnzhgkdylmapviuse\n" +
            "oewmbtcxjqnzbgkdylfaiviurr\n" +
            "oewmbtcxjqnzhkkdyloapsiusr\n" +
            "oewjbtcxjqnhhgkdylfapjiusr\n" +
            "odwmbtcnjqnzhgkdylfapvicsr\n" +
            "oewmbccxjqrzwgkdylfapviusr\n" +
            "kewmbtcvjqnzhgkdylaapviusr\n" +
            "okwmbtcxjqnzhgkdylfspvausr\n" +
            "oewmbtcxjynzhgkdyafapviusw\n" +
            "oewmbtcxjqnzhgwdyleayviusr\n" +
            "oewmbtcxjqnzhgkdylfapviicl\n" +
            "oewmbtcxjqnzhgkdyltaeziusr\n" +
            "oewmbtcxrqnzhgkdylftpvizsr\n" +
            "oewsrtcgjqnzhgkdylfapviusr\n" +
            "oewmbtsxgqnzhgxdylfapviusr\n" +
            "oewmbtcxjanzhgtdylfapeiusr\n" +
            "oewybtcgjqnzhgkdylfapviust\n" +
            "ojwmbncxjqnzhgkdylfapgiusr\n" +
            "ocgebtcxjqnzhgkdylfapviusr\n" +
            "oejcbtcxjqnzhgkvylfapviusr\n" +
            "oswmbtcxjqnkhgkdylfapviusb\n" +
            "oewdbtcxjqnzdgkdylfypviusr\n" +
            "oawmutcxjqnzhgkddlfapviusr\n" +
            "oewzbtcxyqnzhgkdylfapviusy\n" +
            "zewmbtcxjqnzkgkdylwapviusr\n" +
            "aewmbtkxjqnzhgkdylfapviuer\n" +
            "oewmbtcxwqnzhgkdyofapviuur\n" +
            "oewmbtcxjqnzggkdylfapanusr\n" +
            "oewmstcxuqnzhgkdylzapviusr\n" +
            "zewmbtcxjqozhgkdelfapviusr\n" +
            "oewzbtcxjqnahgkdyllapviusr\n" +
            "fewmatcxjqnghgkdylfapviusr\n" +
            "oewmbtcxjqnzhgkdylfapviyqb\n" +
            "oewwbtcxjqnzhgkdyljapviqsr\n" +
            "oewmbtbxjqnzhgkxylfapviesr\n" +
            "oewmbtcbjqnphgkdylfapviysr\n" +
            "oewabtcxyqnzhgkdylfabviusr\n" +
            "oewmbtcxhknzhgkdylfapviusd\n" +
            "ozwmbtcljqnzhgkdylfapviksr\n" +
            "tewmbtcxjqnzhgkdylfaxvqusr\n" +
            "oewmbtcxrqnzhgkdytfapvrusr\n" +
            "ohwmbtcxjcnzhgkdyifapviusr\n" +
            "oewmbpcxjqnzhwkdylfaphiusr\n" +
            "oedmbtcxjqnzhgnbylfapviusr\n" +
            "oewmbocxjqnehgkdylfapvbusr\n" +
            "oeymbtcxjqezegkdylfapviusr\n" +
            "oewmbtcxjqnzhgkdllferviusr\n" +
            "oewmbtcxjqnzhgkwmlfawviusr\n" +
            "oewmbtcxienzhgkdyzfapviusr\n" +
            "mewmbtcxjqnzhqkdylfapviwsr\n" +
            "oewmbtcxjqnztgkmylfapvdusr\n" +
            "ouwmbtcxjqnzhokdylpapviusr\n" +
            "oewmctcxjqhzhgmdylfapviusr\n" +
            "oewmbtcyjqnzhmkdylfarviusr\n" +
            "oewmbtcxjqnzhgkdpnfzpviusr\n" +
            "oewmptcxjqnzhgkdylkapviulr\n" +
            "nefmbtcxsqnzhgkdylfapviusr\n" +
            "oewmbtcxwqnzhgkdilfapvizsr\n" +
            "eewmbtcxjqwzhghdylfapviusr\n" +
            "oewmbtixmqnzhgkjylfapviusr\n" +
            "okwmbtcdzqnzhgkdylfapviusr\n" +
            "oewmbtxxjrnzigkdylfapviusr\n" +
            "oewmdycxjqnzhekdylfapviusr\n" +
            "oewmutcxjqnzhgkdylfapsiuqr\n" +
            "oewmbacxjqnzrgkdrlfapviusr\n" +
            "oewmbtcxpqnzhmkdylfapciusr\n" +
            "oewabtcxjqnzhgkdyrcapviusr\n" +
            "oswmbtcxjqnzhgkdrxfapviusr\n" +
            "gewmbtcnjqnzhgkdylvapviusr\n" +
            "newmbtcxjwnzfgkdylfapviusr\n" +
            "lewmbtcxjqnzhgkdylfaptiujr\n" +
            "oewwbtcxjqndhgkdylfapiiusr\n" +
            "oewmbtcxjqnzhggdylfapvqmsr\n" +
            "lewmbtcxjqnzhgkhllfapviusr\n" +
            "oewmbtocjqnzhgkdylfapvhusr\n" +
            "oedmbtcxjqnzhgkdyhfapviusb\n" +
            "oewmbtcxjqnzhgkdylfajvaosr\n" +
            "zewmbtcxjqnzhgkdylfapvsssr\n" +
            "oewmbthxjqnzhskdylfapviuqr\n" +
            "yewmrtcvjqnzhgkdylfapviusr\n" +
            "oewmbtctjqnzhgkdylfabvhusr\n" +
            "oesmstcxjqnzhgkdylfapqiusr\n" +
            "oewmbtcxjqnzzgkdylfopiiusr\n" +
            "otwmbtzxjqnzhgkdylfaxviusr\n" +
            "ouwmbxcxjqnzhgkdylfapvnusr\n" +
            "oewmbtcxjqezhgedylfapvsusr\n" +
            "oesmhtcsjqnzhgkdylfapviusr\n" +
            "oewdbtcxjqnzhgkdilfapvifsr\n" +
            "oewmbtcxjqnzhgudynfamviusr\n" +
            "qewhbtcxjqnzhgkdyxfapviusr\n" +
            "oewmbzcxjqtzhgkdylfapvitsr\n" +
            "oewmbtccjqzzhgkaylfapviusr\n" +
            "jewmbtcxmqnzhlkdylfapviusr\n" +
            "oewmbtcxjqbzhgkdnlfapviusp\n" +
            "oeimbtcdjqnzhgkdylfapviuer\n" +
            "oewtbtcxjqnihgkdylfahviusr\n" +
            "oewmbtcxhqnzhgkdylfapdiudr\n" +
            "oefmbtcxjqyshgkdylfapviusr\n" +
            "oewmbtcxjqnzhgkfglfapviusx\n" +
            "oecmbocxjqnzhgkdmlfapviusr\n" +
            "oewmbtcxjqnzhghdylfavviuhr\n" +
            "oewmbmcxiqnzhgkpylfapviusr\n" +
            "oewmbtcnjqnzhgkrylfanviusr\n" +
            "oewmbocxjqnzhzkdllfapviusr\n" +
            "eewmbtckjqnzhgkdylfapviusg\n" +
            "oewmbtcrjqqzhgkdylfapvigsr\n" +
            "oewmbtcxjqazhgfdylfapjiusr\n" +
            "oetmbtcxjqnzhgldylfapviqsr\n" +
            "oewbbtcxjqnzlgkdylfapviuse\n" +
            "oewmbtcxjqnzhglbolfapviusr\n" +
            "oewmbtcxjqnzcgkdylfapviuhy\n" +
            "oelmbtcxjqfzhgkdylaapviusr\n" +
            "oojmbycxjqnzhgkdylfapviusr\n" +
            "oewmbtrxjqnrhgkdylfapniusr\n" +
            "oewmbtcxjqnzhgkyyhfapviuso\n" +
            "oewabtcxjqnzhskdylfapviusx\n" +
            "oewmbtcrjqnmhgkdylfapvnusr\n" +
            "oewmbtcxjqrzhgkdylfapvpuss\n" +
            "oewmbtcxhqnzwgkddlfapviusr\n" +
            "kewmbtcxjqnzhgkyylfajviusr\n" +
            "oswmbtcxjqnzhgkdjlfapviuss\n" +
            "onwmbtcxjqnchgkdylfapvpusr\n" +
            "oeymbtcxjqnxhikdylfapviusr\n" +
            "oewmblcdjqnzhgkdylfapviysr\n" +
            "oewmbtcxeqczhgudylfapviusr\n" +
            "oewmbpgxjqnzhgkdylfapfiusr\n" +
            "ohwmwtcxjqnzhgkdylftpviusr\n" +
            "zebmbtuxjqnzhgkdylfapviusr";
}
